pipeline {
    agent {
        docker { image maven:3.8.2-openjdk-8 }

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
    }
}
